### ISSUE TITLE
Job row missing image

### ISSUE THREAD

**Issue by robghchen** [robghchen/tracking-system#14]
![Screen Shot 2020-06-28 at 9 12 06 AM](https://user-images.githubusercontent.com/42457979/85948564-94375380-b91f-11ea-89ce-4a0291415292.png)

Specs:
1. Add the company image to jobRow like how we did for jobCard
2. Use flexbox to move "Salary", "Size", "Industry" to be on the right of company name

Resource: https://flexboxfroggy.com/

**Comment by kyungjunism** [comment]
No image in jobcard in the current tracking-system pull. Looks like version control issue

**Comment by robghchen** [comment]
we can check that out when we meet, in like 30 minutes
